export default {
    'external-entity': { title: 'External Entity (SBOM Ingestion)' },
    admin: { title: 'Admin' },
    'admin-daemons': { title: 'Admin Daemons' },
    advisories: { title: 'Advisories' },
    artifacts: { title: 'Artifacts' },
    'asset-versions': { title: 'Asset Versions' },
    assets: { title: 'Assets' },
    attestations: { title: 'Attestations' },
    authentication: { title: 'Authentication' },
    compliance: { title: 'Compliance' },
    'compliance-components': { title: 'Compliance Components' },
    'compliance-postures': { title: 'Compliance Postures' },
    components: { title: 'Components' },
    crowdsourcedvexing: { title: 'CrowdsourcedVexing' },
    csaf: { title: 'CSAF' },
    'cve-database': { title: 'CVE Database' },
    'dependency-firewall': { title: 'Dependency Firewall' },
    externalreferences: { title: 'ExternalReferences' },
    'in-toto': { title: 'In-toto' },
    integrations: { title: 'Integrations' },
    'license-risk': { title: 'License Risk' },
    organizations: { title: 'Organizations' },
    policies: { title: 'Policies' },
    projects: { title: 'Projects' },
    releases: { title: 'Releases' },
    scanning: { title: 'Scanning' },
    statistics: { title: 'Statistics' },
    system: { title: 'System' },
    vexrules: { title: 'VEXRules' },
    vulndb: { title: 'VulnDB' },
    vulnerabilities: { title: 'Vulnerabilities' },
    'vulnerability-events': { title: 'Vulnerability Events' },
    webhooks: { title: 'Webhooks' },
}
