export default {
    'artifacts': { title: 'Artifacts' },
    'asset-versions': { title: 'Asset Versions' },
    'assets': { title: 'Assets' },
    'attestations': { title: 'Attestations' },
    'authentication': { title: 'Authentication' },
    'csaf': { title: 'CSAF' },
    'cve': { title: 'CVE' },
    'cve-database': { title: 'CVE Database' },
    'externalreferences': { title: 'ExternalReferences' },
    'integrations': { title: 'Integrations' },
    'organizations': { title: 'Organizations' },
    'projects': { title: 'Projects' },
    'releases': { title: 'Releases' },
    'scanning': { title: 'Scanning' },
    'statistics': { title: 'Statistics' },
    'vexrules': { title: 'VEXRules' },
    'vulndb': { title: 'VulnDB' },
    'vulnerabilities': { title: 'Vulnerabilities' },
    'webhooks': { title: 'Webhooks' },
}
