export default {
    index: { theme: { layout: 'raw' }, display: 'hidden' },
    pricing: { theme: { layout: 'raw' }, display: 'hidden' },
    'package-inspector': { theme: { layout: 'raw' }, display: 'hidden' },
    'terms-of-use': { display: 'hidden' },
    'privacy-policy': { display: 'hidden' },
    introduction: { title: 'Introduction' },
    'getting-started': { title: 'Getting Started' },
    tutorials: { title: 'Tutorials' },
    'how-to-guides': { title: 'How-to Guides' },
    reference: { title: 'Reference' },
    explanations: { title: 'Explanations' },
    comparison: { title: 'Comparison' },
    contributing: { title: 'Contributing' },
    other: { title: 'Other' },
    'header-pricing': { title: 'Pricing', type: 'page', href: '/pricing' },
    'header-docs': {
        title: 'Documentation',
        type: 'page',
        href: '/introduction',
    },
    '404': { theme: { layout: 'raw' }, display: 'hidden' },
}
