export default {
    index: { title: 'Overview' },
    'deploy-with-helm': { title: 'Deploy with Helm' },
    'deploy-with-docker': { title: 'Deploy with Docker Compose' },
    'deploy-with-cloudnativepg': { title: 'Deploy with CloudNativePG' },
    'backup-restore': { title: 'Backup & Restore' },
    'monitoring-metrics': { title: 'Monitoring & Metrics' },
    'upgrade-devguard': { title: 'Upgrade DevGuard' },
    'database-maintenance': { title: 'Database Maintenance' },
    'restricting-access': { title: 'OIDC/ SSO & Restricting Access' },
    'instance-admin-dashboard': { title: 'Instance Admin Dashboard' },
    'customize-ui': { title: 'Customize the UI' },
    telemetry: { title: 'Telemetry' },
    'uninstalling-devguard': { title: 'Uninstalling DevGuard' },
}
