export const tiers = [
    {
        name: 'SaaS' as const,
        slug: 'saas',
        description: 'Hassle free. We host DevGuard for you.',
        priceMonthly: 479,
        href: '#',
        highlights: [
            { description: 'Up to 20 team members' },
            { description: 'Up to 50 projects & assets' },
            { description: 'Source leads from select platforms' },
            { description: 'RadiantAI integrations', disabled: true },
            { description: 'Competitor analysis', disabled: true },
        ],
        features: [
            { section: 'Features', name: 'Accounts', value: 3 },
            { section: 'Features', name: 'Deal progress boards', value: 5 },
            {
                section: 'Features',
                name: 'Sourcing platforms',
                value: 'Select',
            },
            { section: 'Features', name: 'Contacts', value: 100 },
            { section: 'Features', name: 'AI assisted outreach', value: false },
            { section: 'Analysis', name: 'Competitor analysis', value: false },
            { section: 'Analysis', name: 'Dashboard reporting', value: false },
            { section: 'Analysis', name: 'Community insights', value: false },
            { section: 'Analysis', name: 'Performance analysis', value: false },
            { section: 'Support', name: 'Email support', value: true },
            {
                section: 'Support',
                name: '24 / 7 call center support',
                value: false,
            },
            {
                section: 'Support',
                name: 'Dedicated account manager',
                value: false,
            },
        ],
    },
    {
        name: 'Enterprise Basic' as const,
        slug: 'enterprise-basic',
        description: 'Contract for essential maintenance and support.',
        priceMonthly: 865,
        startingAt: true,
        href: '#',
        highlights: [
            { description: 'Up to 10 team members' },
            { description: 'Unlimited deal progress boards' },
            { description: 'Source leads from over 50 verified platforms' },
            { description: 'RadiantAI integrations' },
            { description: '5 competitor analyses per month' },
        ],
        features: [
            { section: 'Features', name: 'Accounts', value: 10 },
            {
                section: 'Features',
                name: 'Deal progress boards',
                value: 'Unlimited',
            },
            { section: 'Features', name: 'Sourcing platforms', value: '100+' },
            { section: 'Features', name: 'Contacts', value: 1000 },
            { section: 'Features', name: 'AI assisted outreach', value: true },
            {
                section: 'Analysis',
                name: 'Competitor analysis',
                value: '5 / month',
            },
            { section: 'Analysis', name: 'Dashboard reporting', value: true },
            { section: 'Analysis', name: 'Community insights', value: true },
            { section: 'Analysis', name: 'Performance analysis', value: true },
            { section: 'Support', name: 'Email support', value: true },
            {
                section: 'Support',
                name: '24 / 7 call center support',
                value: true,
            },
            {
                section: 'Support',
                name: 'Dedicated account manager',
                value: false,
            },
        ],
    },
    {
        name: 'Enterprise Advanced' as const,
        slug: 'enterprise-advanced',
        description: 'Added flexibility to close deals at scale.',
        priceMonthly: 1850,
        startingAt: true,
        href: '#',
        highlights: [
            { description: 'Unlimited active team members' },
            { description: 'Unlimited deal progress boards' },
            { description: 'Source leads from over 100 verified platforms' },
            { description: 'RadiantAI integrations' },
            { description: 'Unlimited competitor analyses' },
        ],
        features: [
            { section: 'Features', name: 'Accounts', value: 'Unlimited' },
            {
                section: 'Features',
                name: 'Deal progress boards',
                value: 'Unlimited',
            },
            { section: 'Features', name: 'Sourcing platforms', value: '100+' },
            { section: 'Features', name: 'Contacts', value: 'Unlimited' },
            { section: 'Features', name: 'AI assisted outreach', value: true },
            {
                section: 'Analysis',
                name: 'Competitor analysis',
                value: 'Unlimited',
            },
            { section: 'Analysis', name: 'Dashboard reporting', value: true },
            { section: 'Analysis', name: 'Community insights', value: true },
            { section: 'Analysis', name: 'Performance analysis', value: true },
            { section: 'Support', name: 'Email support', value: true },
            {
                section: 'Support',
                name: '24 / 7 call center support',
                value: true,
            },
            {
                section: 'Support',
                name: 'Dedicated account manager',
                value: true,
            },
        ],
    },
]
