# DevSecOps Workflow Definition
# This workflow is triggered on every push to the repository
name: DevGuard Workflow

on:
  push:
 
jobs:
  devguard-scanner:
    uses: l3montree-dev/devguard-action/.github/workflows/full.yml@main
    with:
        api-url: https://api.main.devguard.org
        asset-name: "l3montree-cybersecurity/projects/devguard/assets/devguard-documentation"
    secrets:
        devguard-token: ${{ secrets.DEVGUARD_TOKEN }}
        build-args: --build-arg=NEXT_PUBLIC_SITE_URL=${{ vars.NEXT_PUBLIC_SITE_URL }} --build-arg=NEXT_PUBLIC_UMAMI_WEBSITE_ID=${{ secrets.NEXT_PUBLIC_UMAMI_WEBSITE_ID }} --build-arg=NEXT_PUBLIC_UMAMI_URL=${{ secrets.NEXT_PUBLIC_UMAMI_URL }} --context=. --dockerfile=Dockerfile