name: "SEO Check"

on:
  push:
  workflow_dispatch:

jobs:
  seo-check:
    runs-on: ubuntu-latest
    container:
      image: registry.opencode.de/open-code/document-writing-tools/seo-check:main-amd64
    steps:
      - uses: actions/checkout@v4
      - name: Copy ISO data files into workspace
        run: cp /seo-check/ISO-639-1-lang-codes.json /seo-check/ISO-3166-Alpha2-country-codes.csv .
      - name: Run SEO-Check
        run: bun run /seo-check/main.ts