name: "SEO Check"

on:
  push:
  workflow_dispatch:

jobs:
  registry-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check registry reachability
        run: curl -I https://registry.opencode.de/v2/

  seo-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run SEO-Check
        uses: docker://registry.opencode.de/open-code/document-writing-tools/seo-check:main-amd64
